theme: jekyll-theme-cayman
title: Accidents Research Project
description: Research and analysis of severity 3 and 4 accidents in the three most accident prone cities in the US. Conducted by Debdip Sengupta and Sai Mali Ananth.
